# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gagiuntoli/fermi:latest

    steps:
    - uses: actions/checkout@v3

    - name: Check syntax
      run: |
        issues=$(clang-format -style=file -output-replacements-xml $(find src include -name '*.c' -o -name '*.h') | grep -c '<replacement ' || true)
        if [ $issues -gt 0 ]; then
          echo "Found formatting issues. Exiting."
          clang-format --dry-run $(find src include -name '*.c' -o -name '*.h') 
          exit 1
        fi
        echo "No syntax issues."

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      run: cmake -Bbuild -H.

    - name: Build with make
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --test_dir ./build
