# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install clang-format for syntax check
      run: sudo apt install -y clang-format

    - name: Check syntax
      run: |
        issues=$(clang-format -style=file -output-replacements-xml $(find src include -name '*.c' -o -name '*.h') | grep -c '<replacement ')
        if [ $issues -gt 0 ]; then
          echo "Found formatting issues. Exiting."
          clang-format --dry-run $(find src include -name '*.c' -o -name '*.h') 
          exit 1
        fi

